env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:mozilla/recommended
  - plugin:react/recommended

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - mozilla
  - react
  - promise

root: true

rules:
  eqeqeq: error
  no-console: [error, {allow: [debug, error, info, trace, warn]}]
  no-var: error
  prefer-const: error

  promise/always-return: off
  promise/avoid-new: off
  promise/catch-or-return: error
  promise/no-callback-in-promise: off
  promise/no-native: off
  promise/no-nesting: off
  promise/no-promise-in-callback: off
  promise/param-names: error
